# Generated by Django 3.1.5 on 2021-04-07 09:49

from django.db import migrations, models
import django.db.models.deletion
import shopadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sugartsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kn', models.CharField(max_length=100, verbose_name='店舗名カナ')),
                ('name_kj', models.CharField(max_length=100, verbose_name='店舗名漢字')),
                ('tel', models.CharField(max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(max_length=20, verbose_name='FAX番号')),
                ('zip', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('address_1', models.CharField(max_length=100, verbose_name='市区郡')),
                ('address_2', models.CharField(max_length=100, verbose_name='住所番地')),
                ('bld', models.CharField(max_length=100, verbose_name='建物等')),
                ('pref_id', models.ForeignKey(default=shopadmin.models.get_default_pref, on_delete=django.db.models.deletion.CASCADE, to='sugartsa.pref', verbose_name='都道府県')),
            ],
        ),
    ]
